version: '3.8'
services:
  user-service-cache:
    image: redis:latest
    container_name: user-service-cache
    restart: unless-stopped
    environment:
      - REDIS_USER=user
      - REDIS_PASSWORD=password
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '16379:6379'
    volumes:
      - user-service-cache-data:/data
    networks:
      - user-service-net
  user-service-db:
    image: "postgres:latest"
    container_name: user-service-db
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data
volumes:
  user-service-cache-data:
  user-service-db-data:
networks:
  user-service-net: