server:
  port: 18082
  servlet:
    context-path: /users
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${ARCHIPIO_USER_SERVICE_DB_URL}/${ARCHIPIO_USER_SERVICE_DB_NAME}
    username: ${ARCHIPIO_USER_SERVICE_DB_USER}
    password: ${ARCHIPIO_USER_SERVICE_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${ARCHIPIO_USER_SERVICE_DB_URL}/${ARCHIPIO_USER_SERVICE_DB_NAME}
    user: ${ARCHIPIO_USER_SERVICE_DB_USER}
    password: ${ARCHIPIO_USER_SERVICE_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${ARCHIPIO_USER_SERVICE_CACHE_HOST}
      port: ${ARCHIPIO_USER_SERVICE_CACHE_PORT}
      password: ${ARCHIPIO_USER_SERVICE_CACHE_PASSWORD}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
